 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sMM.interfaz;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import sMM.basededatos.ConexionBD;
import sMM.basededatos.ConexionJDBC;
import sMM.modelo.Disco;

/**
 *
 * @author Eloy
 */
public class AddDiscoFrame extends javax.swing.JFrame {
    // Variables para mover ventana desde la barra de titulo (Dragger)
    Point start_drag;
    Point start_loc;
    boolean dragging;
    MainFrame mFrame;
    /**
     * Creates new form addDiscoFrame
     */
    public AddDiscoFrame(MainFrame f) {
        mFrame = f;
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    Point getScreenLocation(MouseEvent e) {
        Point cursor = e.getPoint();
        Point target_location = this.getLocationOnScreen();
        return new Point((int) (target_location.getX() + cursor.getX()),
            (int) (target_location.getY() + cursor.getY()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        tituloField = new javax.swing.JTextField();
        AnoSalidaField = new javax.swing.JTextField();
        AceptarButton = new javax.swing.JLabel();
        barrasLabel = new javax.swing.JLabel();
        barrasLabel1 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Dragger = new javax.swing.JPanel();
        AnoEdicionField = new javax.swing.JTextField();
        NumeroCatalogoField = new javax.swing.JTextField();
        PosicionEnUbicacionField = new javax.swing.JTextField();
        ValoracionField = new javax.swing.JTextField();
        PaisEdicionField = new javax.swing.JTextField();
        CodigoBarrasField = new javax.swing.JTextField();
        barrasLabel2 = new javax.swing.JLabel();
        barrasLabel3 = new javax.swing.JLabel();
        barrasLabel4 = new javax.swing.JLabel();
        barrasLabel5 = new javax.swing.JLabel();
        FechaCompraField = new javax.swing.JTextField();
        barrasLabel6 = new javax.swing.JLabel();
        PrecioCompraField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        NotasField = new javax.swing.JTextArea();
        barrasLabel7 = new javax.swing.JLabel();
        barrasLabel8 = new javax.swing.JLabel();
        barrasLabel9 = new javax.swing.JLabel();
        CodigoColeccionField = new javax.swing.JTextField();
        barrasLabel10 = new javax.swing.JLabel();
        barrasLabel11 = new javax.swing.JLabel();
        barrasLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 30));
        setUndecorated(true);

        Base.setBackground(new java.awt.Color(70, 70, 70));
        Base.setToolTipText("");

        tituloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloFieldActionPerformed(evt);
            }
        });

        AnoSalidaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoSalidaFieldActionPerformed(evt);
            }
        });

        AceptarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AceptarButton.setText("Aceptar");
        AceptarButton.setOpaque(true);
        AceptarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarButtonMouseClicked(evt);
            }
        });

        barrasLabel.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel.setText("Titulo (Este Valor es Obligatorio)");

        barrasLabel1.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel1.setText("Año de Salida");

        Cerrar.setBackground(new java.awt.Color(50, 50, 50));
        Cerrar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cerrar.setText("X");
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CerrarMouseReleased(evt);
            }
        });

        Minimizar.setBackground(new java.awt.Color(50, 50, 50));
        Minimizar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimizar.setText("_");
        Minimizar.setMaximumSize(new java.awt.Dimension(50, 35));
        Minimizar.setMinimumSize(new java.awt.Dimension(50, 35));
        Minimizar.setName(""); // NOI18N
        Minimizar.setPreferredSize(new java.awt.Dimension(50, 35));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MinimizarMouseReleased(evt);
            }
        });

        Dragger.setBackground(new java.awt.Color(70, 70, 70));
        Dragger.setForeground(new java.awt.Color(0, 255, 0));
        Dragger.setPreferredSize(new java.awt.Dimension(925, 35));
        Dragger.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DraggerMouseDragged(evt);
            }
        });
        Dragger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DraggerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DraggerLayout = new javax.swing.GroupLayout(Dragger);
        Dragger.setLayout(DraggerLayout);
        DraggerLayout.setHorizontalGroup(
            DraggerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DraggerLayout.setVerticalGroup(
            DraggerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        AnoEdicionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoEdicionFieldActionPerformed(evt);
            }
        });

        NumeroCatalogoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroCatalogoFieldActionPerformed(evt);
            }
        });

        PosicionEnUbicacionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosicionEnUbicacionFieldActionPerformed(evt);
            }
        });

        barrasLabel2.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel2.setText("Año de la Edición");

        barrasLabel3.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel3.setText("Numero de Catalogo");

        barrasLabel4.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel4.setText("Codigo de Barras");

        barrasLabel5.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel5.setText("Fecha de Compra (YYYY-MM-DD)");

        FechaCompraField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaCompraFieldActionPerformed(evt);
            }
        });

        barrasLabel6.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel6.setText("Precio de Compra");

        PrecioCompraField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioCompraFieldActionPerformed(evt);
            }
        });

        NotasField.setColumns(20);
        NotasField.setRows(5);
        jScrollPane1.setViewportView(NotasField);

        barrasLabel7.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel7.setText("Notas sobre el Disco");

        barrasLabel8.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel8.setText("Valoración");

        barrasLabel9.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel9.setText("Pais de la Edicion");

        barrasLabel10.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel10.setText("Codigo de Coleccion");

        barrasLabel11.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel11.setText("Posicion En Ubicacion");

        barrasLabel12.setForeground(new java.awt.Color(255, 255, 255));
        barrasLabel12.setText("Por Favor, Añada los datos correspondientes al disco que quiera agregar");

        javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
        Base.setLayout(BaseLayout);
        BaseLayout.setHorizontalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaseLayout.createSequentialGroup()
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BaseLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(barrasLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(barrasLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AnoEdicionField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NumeroCatalogoField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(barrasLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AnoSalidaField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(barrasLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(barrasLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CodigoBarrasField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tituloField)
                                .addComponent(CodigoColeccionField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                            .addComponent(barrasLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BaseLayout.createSequentialGroup()
                                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(barrasLabel11)
                                    .addComponent(PosicionEnUbicacionField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrecioCompraField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValoracionField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PaisEdicionField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barrasLabel9)
                                    .addComponent(barrasLabel6)
                                    .addComponent(FechaCompraField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barrasLabel5)
                                    .addComponent(barrasLabel8)
                                    .addComponent(AceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barrasLabel7)))
                            .addComponent(barrasLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BaseLayout.createSequentialGroup()
                        .addComponent(Dragger, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BaseLayout.setVerticalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaseLayout.createSequentialGroup()
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Dragger, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(barrasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barrasLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barrasLabel1)
                    .addComponent(barrasLabel7)
                    .addComponent(barrasLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnoSalidaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaCompraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barrasLabel2)
                            .addComponent(barrasLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnoEdicionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrecioCompraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barrasLabel3)
                            .addComponent(barrasLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroCatalogoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValoracionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barrasLabel4)
                            .addComponent(barrasLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoBarrasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaisEdicionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barrasLabel10)
                            .addComponent(barrasLabel11))
                        .addGap(7, 7, 7)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PosicionEnUbicacionField)
                            .addComponent(CodigoColeccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarButtonMouseClicked
                                                  
        if (evt.getButton() == 1) {
            if (tituloField.getText().compareTo("") == 0) {
                tituloField.setBackground(Color.red);
            } else {
                ConexionBD BD;

		BD = ConexionJDBC.getInstance();
                Disco disc = new Disco(0);
                if (tituloField.getText().compareTo("") != 0)
                {
                    disc.setTitulo(tituloField.getText());
                }
                if (AnoSalidaField.getText().compareTo("") != 0)
                {
                    disc.setAnoSalida(Integer.parseInt(AnoSalidaField.getText())); 
                }
                if (AnoEdicionField.getText().compareTo("") != 0)
                {
                   disc.setAnoEdicion(Integer.parseInt(AnoEdicionField.getText()));
                }
                if (NumeroCatalogoField.getText().compareTo("") != 0)
                {
                   disc.setNumeroCatalogo(NumeroCatalogoField.getText());
                }
                if (CodigoBarrasField.getText().compareTo("") != 0)
                {
                   disc.setNumeroCatalogo(CodigoBarrasField.getText());
                }
                if (CodigoColeccionField.getText().compareTo("") != 0)
                {
                   disc.setNumeroCatalogo(NumeroCatalogoField.getText());
                }
                if (FechaCompraField.getText().compareTo("") != 0)
                {
                   disc.setFechaCompra(FechaCompraField.getText());
                }
                if (PrecioCompraField.getText().compareTo("") != 0)
                {
                   disc.setAnoEdicion(Integer.parseInt(PrecioCompraField.getText()));
                }
                if (NotasField.getText().compareTo("") != 0)
                {
                   disc.setNotas(NotasField.getText());
                }
                if (ValoracionField.getText().compareTo("") != 0)
                {
                   disc.setValoracion(Float.parseFloat(ValoracionField.getText()));
                }
                if (PaisEdicionField.getText().compareTo("") != 0)
                {
                   disc.setNotas(PaisEdicionField.getText());
                }
                if (PosicionEnUbicacionField.getText().compareTo("") != 0)
                {
                   disc.setNotas(PosicionEnUbicacionField.getText());
                }
                
    

                BD.añadirDisco(disc);
                mFrame.consultarDiscos();
                mFrame.mensajeDiscoCreado();
                dispose();
            }
            //MainFrame.getDatosUsuario();
        }
    }//GEN-LAST:event_AceptarButtonMouseClicked

    private void tituloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloFieldActionPerformed

    private void AnoSalidaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoSalidaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoSalidaFieldActionPerformed

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        if (evt.getButton() == 1) {
            dispose();
        }
    }//GEN-LAST:event_CerrarMouseClicked

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        Cerrar.setOpaque(true);
        Cerrar.setForeground(Color.red);
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        Cerrar.setOpaque(false);
        Cerrar.setForeground(Color.white);
    }//GEN-LAST:event_CerrarMouseExited

    private void CerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMousePressed

    private void CerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseReleased

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        if (evt.getButton() == 1) this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseEntered
        Minimizar.setOpaque(true);
        Minimizar.setForeground(Color.CYAN);
    }//GEN-LAST:event_MinimizarMouseEntered

    private void MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseExited
        Minimizar.setOpaque(false);
        Minimizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_MinimizarMouseExited

    private void MinimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizarMousePressed

    private void MinimizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizarMouseReleased

    private void DraggerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggerMouseDragged
        // Genera movimiento de la ventana
        if (this.getExtendedState() == JFrame.NORMAL && dragging) {
            Point current = this.getScreenLocation(evt);
            Point offset = new Point((int) current.getX() - (int) start_drag.getX(),
                (int) current.getY() - (int) start_drag.getY());
            Point new_location = new Point(
                (int) (this.start_loc.getX() + offset.getX()), (int) (this.start_loc
                    .getY() + offset.getY()));
            this.setLocation(new_location);
        }
    }//GEN-LAST:event_DraggerMouseDragged

    private void DraggerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggerMousePressed
        // Se empieza a mover ventana
        if (evt.getButton() == 1 && this.getExtendedState() == JFrame.NORMAL) {
            dragging = true;
            this.start_drag = this.getScreenLocation(evt);
            this.start_loc = this.getLocation();
        }
    }//GEN-LAST:event_DraggerMousePressed

    private void AnoEdicionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoEdicionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoEdicionFieldActionPerformed

    private void NumeroCatalogoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroCatalogoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCatalogoFieldActionPerformed

    private void FechaCompraFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaCompraFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaCompraFieldActionPerformed

    private void PrecioCompraFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioCompraFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioCompraFieldActionPerformed

    private void PosicionEnUbicacionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosicionEnUbicacionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosicionEnUbicacionFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDiscoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDiscoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDiscoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDiscoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new addDiscoFrame().setVisible(true);
            //}
        //});
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new addDiscoFrame().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AceptarButton;
    private javax.swing.JTextField AnoEdicionField;
    private javax.swing.JTextField AnoSalidaField;
    private javax.swing.JPanel Base;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JTextField CodigoBarrasField;
    private javax.swing.JTextField CodigoColeccionField;
    private javax.swing.JPanel Dragger;
    private javax.swing.JTextField FechaCompraField;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JTextArea NotasField;
    private javax.swing.JTextField NumeroCatalogoField;
    private javax.swing.JTextField PaisEdicionField;
    private javax.swing.JTextField PosicionEnUbicacionField;
    private javax.swing.JTextField PrecioCompraField;
    private javax.swing.JTextField ValoracionField;
    private javax.swing.JLabel barrasLabel;
    private javax.swing.JLabel barrasLabel1;
    private javax.swing.JLabel barrasLabel10;
    private javax.swing.JLabel barrasLabel11;
    private javax.swing.JLabel barrasLabel12;
    private javax.swing.JLabel barrasLabel2;
    private javax.swing.JLabel barrasLabel3;
    private javax.swing.JLabel barrasLabel4;
    private javax.swing.JLabel barrasLabel5;
    private javax.swing.JLabel barrasLabel6;
    private javax.swing.JLabel barrasLabel7;
    private javax.swing.JLabel barrasLabel8;
    private javax.swing.JLabel barrasLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tituloField;
    // End of variables declaration//GEN-END:variables
}
